### ISSUE TITLE
CFG Lock 可以在BIOS里修改

### ISSUE THREAD

**Issue by Xiiqiing** [capricornlee/LG-Gram13-Z990#10]
BIOS-Advanced-Intel Advanced Menu-Power&Performance-CPU Power Management Control: CFG Lock [Disabled]，
参见https://github.com/suzuke/LG-Gram-13z980-Opencore 。

--------------------------

这个BIOS高级设置保存后重启有概率恢复成默认，我没找到永久保存方法。

**Comment by capricornlee** [comment]
噢 谢谢 这个方法出自我的issues里一位热心朋友，是有几率重置，但各种修改bios方法我试过都不行 暂时先用这种
