### ISSUE TITLE
14z990 HDMI输出

### ISSUE THREAD

**Issue by myd986** [capricornlee/LG-Gram13-Z990#11]
使用楼主的efi 只修改了序列号等信息，HDMI无输出，之前提交issue楼主表示自己的13z990正常，如果有其他同学hdmi无输出的可以参考下我的配置
![Screen Shot 2020-07-06 at 10 51 17 AM](https://user-images.githubusercontent.com/49913958/86551209-025ec480-bf77-11ea-9674-f5dec61ecf52.png)

**Comment by myd986** [comment]
这里使用的是[luoliang](https://github.com/YGQ8988/HP-ProBook430G6)的缓冲帧补丁

**Comment by capricornlee** [comment]
是的 因为DP与HDMI输出都是con1，con1的type改为00080000为HDMI 00040000为DP，不填默认是DP
