### ISSUE TITLE
无法U盘引导，推测是secureboot关不掉造成

### ISSUE THREAD

**Issue by cfqbridge** [capricornlee/LG-Gram13-Z990#12]
BIOS是19年3月25日的版本，W1ZD1210，可以按Ctrl+Alt+F2进隐藏项，但是关闭Secure Boot的选项无法保存。重启就会失效，U盘无法引导启动。不知道有没有做错什么，会不会有其他原因。

**Comment by capricornlee** [comment]
可以升级一下BIOS版本 官网有新版的，安全启动如果不关的确是进不了U盘我刚开始体验过。

**Comment by Shawithyou** [comment]
请教一下蓝牙问题。我买了943602cs还有转接卡等等，蓝牙线是直接焊在金手指正面吗，我焊上插到了usb口里，系统没发生什么变化，通过ioregistryExplorer、hackintools、苹果系统报告里也没发现 有有关蓝牙的设备，我不知道是不是焊的有问题，如何确定我焊对? （博通网卡的无线网络是正常使用的，蓝牙无法使用）
另外定制usb端口，屏蔽原来intel网卡的蓝牙端口，这个具体要怎么操作呢。是否是像这篇文章一样https://www.cnblogs.com/jifeng/p/9126362.html。

**Comment by cfqbridge** [comment]
> 可以升级一下BIOS版本 官网有新版的，安全启动如果不关的确是进不了U盘我刚开始体验过。

应该是Bios自动重置的锅，重复设置了七八轮，总算是关掉了。官网现在没有了Bios下载，不知道是不是近期要更新。

**Comment by capricornlee** [comment]
> 请教一下蓝牙问题。我买了943602cs还有转接卡等等，蓝牙线是直接焊在金手指正面吗，我焊上插到了usb口里，系统没发生什么变化，通过ioregistryExplorer、hackintools、苹果系统报告里也没发现 有有关蓝牙的设备，我不知道是不是焊的有问题，如何确定我焊对? （博通网卡的无线网络是正常使用的，蓝牙无法使用）
> 另外定制usb端口，屏蔽原来intel网卡的蓝牙端口，这个具体要怎么操作呢。是否是像这篇文章一样[https://www.cnblogs.com/jifeng/p/9126362.html。](https://www.cnblogs.com/jifeng/p/9126362.html%E3%80%82)

要用免驱卡蓝牙的话 需要先屏蔽原有的蓝牙，在hackintools可以定制 参考下：https://blog.daliansky.net/Intel-FB-Patcher-tutorial-and-insertion-pose.html 定制USB部分。我是直接焊在金手指正面的 中间两个端子就是d+/d- 如果两根线没焊对就对换一下，如果对了且屏蔽好原有蓝牙，插上去就能识别到
