### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by jydjygv** [capricornlee/LG-Gram13-Z990#13]
I am trying to install Catalina version 10.15.6 on my LG gram 13 13Z990-A.AAS5U1 and I used the exact same EFI folder you provided but the trackpad is not working

**Comment by myd986** [comment]
There is an idea. First, check whether the VoodooI2C State has been loaded by GenI2C. If the program show it has been loaded, you might need to review your DSDT with the help of [this web](https://voodooi2c.github.io). I'm just a beginner of hackintosh, but I believe the trackpad will work after reviewing DSDT.

**Comment by myd986** [comment]
There is an idea. Above all, check whether the VoodooI2C State has been loaded by GenI2C. If the program shows it has been loaded, you might need to review your DSDT with the help of [this web](https://voodooi2c.github.io). I'm just a beginner of hackintosh, but I believe the trackpad will work after reviewing DSDT.
