### ISSUE TITLE
我想请问一下，怎么驱动触控板。我是z990。

### ISSUE THREAD

**Issue by bze9399** [capricornlee/LG-Gram13-Z990#17]
我用了你的文件，很感谢。驱动成功了。
现在除了触控板不能驱动，其他的都没什么问题了。
您如果方便的话，能不能做个视频。或者告诉我该怎么做。
不好意思，打扰您了。

**Comment by capricornlee** [comment]
readme里面有介绍触摸板的驱动方式，或者你用GenI2C软件 先查一下你的设备APIC Pin是多少

**Comment by myd986** [comment]
我是14z990，刚升级了efi，用上一个版本的efi是可以驱动的（也许我之前不能驱动我自己修改过，我忘记了），这次更新后触控板不能用了，尝试升级触控板相关的驱动文件就行了。[VoodooPS2](https://github.com/acidanthera/VoodooPS2)和[VoodooI2C](https://github.com/VoodooI2C/VoodooI2C)，把相同的kext文件替换进去就可以了，希望能帮到你。
顺便说一下，上个版本的efi可以通过fn+prtsc键快速打开和关闭触控板，不知道是不是作者有意为之，这个版本把这个快捷键修正回了截图，好评！！！用着很方便，但还是希望能有一个触控板的快捷键，dream一个fn+f5，先谢谢作者大佬了～～～

**Comment by 2xproxy** [comment]
> 我是14z990，刚升级了efi，用上一个版本的efi是可以驱动的（也许我之前不能驱动我自己修改过，我忘记了），这次更新后触控板不能用了，尝试升级触控板相关的驱动文件就行了。[VoodooPS2](https://github.com/acidanthera/VoodooPS2)和[VoodooI2C](https://github.com/VoodooI2C/VoodooI2C)，把相同的kext文件替换进去就可以了，希望能帮到你。
> 顺便说一下，上个版本的efi可以通过fn+prtsc键快速打开和关闭触控板，不知道是不是作者有意为之，这个版本把这个快捷键修正回了截图，好评！！！用着很方便，但还是希望能有一个触控板的快捷键，dream一个fn+f5，先谢谢作者大佬了～～～

VoodooPS2和VoodooI2C裹面的文件名字要自己改成kext? 
具體有那些文件要進行替換 感謝

**Comment by 2xproxy** [comment]
> 我是14z990，刚升级了efi，用上一个版本的efi是可以驱动的（也许我之前不能驱动我自己修改过，我忘记了），这次更新后触控板不能用了，尝试升级触控板相关的驱动文件就行了。[VoodooPS2](https://github.com/acidanthera/VoodooPS2)和[VoodooI2C](https://github.com/VoodooI2C/VoodooI2C)，把相同的kext文件替换进去就可以了，希望能帮到你。
> 顺便说一下，上个版本的efi可以通过fn+prtsc键快速打开和关闭触控板，不知道是不是作者有意为之，这个版本把这个快捷键修正回了截图，好评！！！用着很方便，但还是希望能有一个触控板的快捷键，dream一个fn+f5，先谢谢作者大佬了～～～

感謝 已解決touchpad問題
