### ISSUE TITLE
Bluetooth

### ISSUE THREAD

**Issue by jydjygv** [capricornlee/LG-Gram13-Z990#18]
I have installed a compatible bcm network card and have attached the wires to the usb for bluetooth and it is showing up in the usb device tree but it is not working.

**Comment by capricornlee** [comment]
Has the Intel Bluetooth USB port been blocked？

**Comment by jydjygv** [comment]
I am not sure I am using your USB port kext and ssdts and the hs10 port has been blocked In the config.plist with a boot argument

**Comment by capricornlee** [comment]
Use Hackintool to check if the bluetooth device only has bcm bluetooth. Try to re-customize the USB port kext.

**Comment by jydjygv** [comment]
It has both intel and bcm

**Comment by jydjygv** [comment]
I tried to deleting intel but it won't let me

**Comment by capricornlee** [comment]
Maybe my machine is different from yours.
Re-customize USB port kext with Hackintool.

**Comment by jydjygv** [comment]
I disabled the intel usb using hack into and it is working now. Thank you

**Comment by jydjygv** [comment]
Hackintool

**Comment by jydjygv** [comment]
How were you able to attach the Bluetooth cable to the usb without soldering? I followed the link but it was not helpful.

**Comment by capricornlee** [comment]
There is no solution using OTG adapters, which is unstable. 
Use the new consumables in the README and fix them with hot melt glue.

**Comment by jydjygv** [comment]
Could you provide a link to the consumables I can't find where to buy them

**Comment by capricornlee** [comment]
I bought it on Taobao but it does not support shipping to foreign countries.

**Comment by jydjygv** [comment]
Can I have the name of the product

**Comment by capricornlee** [comment]
Original name: USB Gold Finger.

**Comment by jydjygv** [comment]
Have you had any success with intel Bluetooth?

**Comment by capricornlee** [comment]
Intel Bluetooth can be driven, but some devices cannot be connected, so it is not used.
You can refer to this https://github.com/OpenIntelWireless/IntelBluetoothFirmware.
