### ISSUE TITLE
sd读卡器驱动

### ISSUE THREAD

**Issue by myd986** [capricornlee/LG-Gram13-Z990#19]
亲测sd读卡器可以用Sinetek-rtsx.kext驱动，扔others里就行
[Sinetek-rtsx.kext.zip](https://github.com/capricornlee/LG-Gram13-Z990/files/5200078/Sinetek-rtsx.kext.zip)

**Comment by capricornlee** [comment]
非常感谢，之前没用用到SD卡 一直没考虑这个
