### ISSUE TITLE
无法进入安装器

### ISSUE THREAD

**Issue by 868686868** [capricornlee/LG-Gram13-Z990#20]
您好
电脑是LG Gram 13Z990 i7-8550u 16G内存
用黑果小兵的镜像 做完USB后原封不动地替换使用您的EFI
现在无法进入安装器 直接尝试启动会黑屏无反应
打开 -v -x 选项启动看到出现memory panic

https://streamable.com/0qft2i
日志全录下了 求大神帮我看下问题出在哪里

试了整天了 这些全都尝试过了:
10.15.0 到 10.15.6 试了全部不行
删除所有分区并初始化SSD
BIOS更新到最新版本W1ZD1250
BIOS还原默认设置
Secure Boot已关
换了不同U盘
更新EFI里clover版本到最新
更新EFI里部分kext版本到最新 (我是小白,复杂的操作不太会)

**Comment by jydjygv** [comment]
Try turning off safe mode in bios

**Comment by 868686868** [comment]
@jydjygv
Sorry, I do not know where is safe mode setting in BIOS, can you say more detail? If you mean secure boot, I turn it off already.

**Comment by 868686868** [comment]
@jydjygv
Sorry, I do not know where is safe mode setting in BIOS, can you say more detail? If you mean secure boot, I turn it off already.

**Comment by 868686868** [comment]
@jydjygv
Sorry, I do not know where is safe mode setting in BIOS, can you say more detail? If you mean secure boot, I turn it off already.

**Comment by 868686868** [comment]
@jydjygv
Sorry, I do not know where is safe mode setting in BIOS, can you say more detail? If you mean secure boot, I turn it off already.

**Comment by 868686868** [comment]
@jydjygv
Sorry, I do not know where is safe mode setting in BIOS, can you say more detail? If you mean secure boot, I turn it off already.

**Comment by 868686868** [comment]
@jydjygv
Sorry, I do not know where is safe mode setting in BIOS, can you say more detail? If you mean secure boot, I turn it off already.

**Comment by 868686868** [comment]
@jydjygv
Sorry, I do not know where is safe mode setting in BIOS, can you say more detail? If you mean secure boot, I turn it off already.

**Comment by 868686868** [comment]
@jydjygv
Sorry, I do not know where is safe mode setting in BIOS, can you say more detail? If you mean secure boot, I turn it off already.

**Comment by 868686868** [comment]
@jydjygv
Sorry, I do not know where is safe mode setting in BIOS, can you say more detail? If you mean secure boot, I turn it off already.

**Comment by jydjygv** [comment]
[LG GRAM EFI.zip](https://github.com/capricornlee/LG-Gram13-Z990/files/5213593/LG.GRAM.EFI.zip)
try this EFI

**Comment by jydjygv** [comment]
yes secure boot is what i meant to say sorry

**Comment by 868686868** [comment]
@jydjygv AMAZING I can boot to installer now. I did not solve for the whole day but you help me solve in a few minutes. Thank you so much, you are so great.

**Comment by 868686868** [comment]
Installation finish perfectly, even trackpad works. Once again, very sincerely THANK YOU.
