### ISSUE TITLE
触控板无法驱动

### ISSUE THREAD

**Issue by windseeker-chen** [capricornlee/LG-Gram13-Z990#3]
我的是14Z990，用了你的efi，发现触控板不生效，显卡也不能调亮度

**Comment by capricornlee** [comment]
触控板需要给DSDT打补丁 OS  Check Fix (window 10)，然后配合驱动，我手上没有14，不知道触控板的范围是否在轮询模式，如果不在可能需要自己修改DSDT使用中断模式
