### ISSUE TITLE
macOS  版本问题

### ISSUE THREAD

**Issue by myd986** [capricornlee/LG-Gram13-Z990#5]
求问机型和macOS版本，试着装了10.14和10.15.1都失败了，都是从App Store下载的。14z990

**Comment by capricornlee** [comment]
我最开始是装14.6，然后升级到15.1，再升级到15.4 一直无痛升级 机型的话 目前用着mbp15,2。暂时没什么问题 安装失败是什么提示？

**Comment by myd986** [comment]
使用之前的efi文件安装卡在内存了，这次更新efi后可以完成安装，可我这里出现了两个问题：1.雷电口无法识别usb3设备，用C to L的线接iPhone能识别，usb3的设备却无法识别，没有雷电设备不能测试雷电功能；2.i2c触控板完全无法工作，我在想是我哪里设置错了吗？或者bios里设置的不对？bios里我只关闭了tpm设备

**Comment by myd986** [comment]
折腾了一天，也没成功，最后试着把Voodooi2c版本从2.4.1替换成2.4.2版本就能行了，触控板可以了之后，c口的usb3连接也正常了，不知道为什么，谢谢大佬了！！！

**Comment by capricornlee** [comment]
哈··触控板驱动方法readme我写上了 跟usb口貌似没有关联···这次也是更新驱动而已
