### ISSUE TITLE
雷雳接口无法识别

### ISSUE THREAD

**Issue by crcu** [capricornlee/LG-Gram13-Z990#6]
机型为14Z990，使用USB-C接口连接手机时只能进行慢速充电，并不能提供18W PD，也不能识别手机

**Comment by myd986** [comment]
同14z990，你能识别到雷电口的usb3吗？我usb3设备连接上去只能识别成usb2设备480Mbps的速度，倒是可以给我的小8快充（我自己重新定制了usb，efi里本身的usb我连雷电口的usb2都识别不到）

**Comment by crcu** [comment]
我用的是USB-C的双公线连接手机，一点动静都没有

**Comment by myd986** [comment]
> 我用的是USB-C的双公线连接手机，一点动静都没有

你用hackintool看过usb了吗？接上手机hackintool能识别吗？

**Comment by capricornlee** [comment]
USB最好还是自己定制一下，毕竟机型不一样。
雷电口要有雷电扩展坞才能用起来 不是随便一条type-c线就能识别为雷电，苹果系统上雷电跟win有点不一样，而且我也没设备测试雷电，平时用不到

**Comment by myd986** [comment]
我现在用usbinjectall+解除端口限制，type-c口都把usb3 hub识别为usb2
![Screen Shot 2020-05-25 at 1 04 49 PM](https://user-images.githubusercontent.com/49913958/82780011-53639f00-9e88-11ea-916e-9182e6431969.png)

**Comment by myd986** [comment]
[usb定制.zip](https://github.com/capricornlee/LG-Gram13-Z990/files/4677254/usb.zip)
可以试一下我定制的usb，我这是可以用了，要删除SSDT-TB3，不然识别不到c口的usb3，不知道为什么，不过这样就没有雷电了。14z990

**Comment by crcu** [comment]
> [usb定制.zip](https://github.com/capricornlee/LG-Gram13-Z990/files/4677254/usb.zip)
> 可以试一下我定制的usb，我这是可以用了，要删除SSDT-TB3，不然识别不到c口的usb3，不知道为什么，不过这样就没有雷电了。14z990

好用，谢谢大佬
