### ISSUE TITLE
关于bios W1ZD1250 修改CFG和DVMT的方法

### ISSUE THREAD

**Issue by as695336480** [capricornlee/LG-Gram13-Z990#7]
开机按F2进入BIOS后 按键盘 CTRL+ALT+F7 可调出隐藏的选项，在Advanced>Intel Advanced Menu>Power & Performance>CPU - Power Management Control>CPU Lock Configuration>CFG LOCK种可以设置  
DVMT也在Advanced 选项种
另外请问一下安装完后没有变频有解决方法吗？

**Comment by capricornlee** [comment]
非常感谢 我明天测试一下能否修改，我这EFI变频没有问题 10档变频

**Comment by capricornlee** [comment]
我是在clover设置里面，ACPI设置->勾选‘插件类型’

**Comment by as695336480** [comment]
我的设备是14Z990 不知道是否是我硬件版本的原因还是您未把最新驱动同步到github的原因，在使用您的EFI后触摸板和屏幕亮度F2、F3无法控制，cpu无法变频，始终保持2.7Ghz以上发热非常严重，能否麻烦您发送一份最新的EFI项目到我邮箱 78090080@qq.com  万分感谢

**Comment by capricornlee** [comment]
这个是最新的 触摸板是打补丁就能驱动 添加补丁 change _OSI to XOSI，配合SSDT-XOSI.aml，或者先用工具查一下14的触摸板APIC Pin，屏幕亮度是系统设置里面，键盘快捷键设置 把亮度调节设置为F2、F3，目前没有时间改fn+Fx的功能键。CPU变频是插件类型加上CPUFirend.kext实现的。

**Comment by capricornlee** [comment]
这里有一个触摸板教程可以参考一下：https://www.penghubingzhou.cn/2019/01/06/VoodooI2C%20DSDT%20Edit/
我当时是看这个教程驱动的，如果14z990的APIC Pin跟13的不一样 可能要用到里面的其他方法来驱动。

**Comment by suzuke** [comment]
首先先感謝 @as695336480  提供修改BIOS隱藏選項的方法，免去了繁瑣的步驟，萬分感謝!

另外我稍微看了一下z990的dsdt, FN Key的部分基本上應該跟z980差異不大，如果有使用_OSI to XOSI更名，FN+F2跟FN+F3分別應該是對應到EC Query裡的_Q50, _Q51，可以參考[OC-little](https://github.com/daliansky/OC-little/tree/master/14-%E4%BA%AE%E5%BA%A6%E5%BF%AB%E6%8D%B7%E9%94%AE) 亮度相關做補丁修正。

如果沒有使用_OSI to XOSI更名，則FN+F2, FN+F3都會對應到_Q40，則可以參考[我的作法](https://github.com/suzuke/LG-Gram-13z980-Opencore/blob/master/ACPI_Patch/SSDT-FNKey.dsl)

_OSI to XOSI更名的部分主要是要用來啟用I2C觸控板 (I2C必須要win8以上才有支援)，但我選擇另外一種方式，屏蔽原有的TPD0, 然後複製出另外一份TPDX, 可以參考[這裡](https://github.com/suzuke/LG-Gram-13z980-Opencore/blob/master/ACPI_Patch/SSDT-TPXX.dsl)

當然以上都僅供慘考，還是要詳細閱讀自己DSDT跟SSDT後再做修改使用，直接使用應該會有問題。

**Comment by ShiningXu** [comment]
🐂🍺呀，没想到BIOS还有隐藏选项 👍👍👍

**Comment by z98785z** [comment]
> 我的设备是14Z990 不知道是否是我硬件版本的原因还是您未把最新驱动同步到github的原因，在使用您的EFI后触摸板和屏幕亮度F2、F3无法控制，cpu无法变频，始终保持2.7Ghz以上发热非常严重，能否麻烦您发送一份最新的EFI项目到我邮箱 [78090080@qq.com](mailto:78090080@qq.com) 万分感谢

https://github.com/stevezhengshiqi/one-key-cpufriend
One-key-cpufriend 可以设置十档变频及cpu省电模式
