### ISSUE TITLE
Intel蓝牙驱动问题

### ISSUE THREAD

**Issue by Whozki** [capricornlee/LG-Gram13-Z990#8]
把intel蓝牙驱动塞进驱动文件夹之后，并没有成功驱动。是不是还有别的设置？

**Comment by myd986** [comment]
是不是没有重新定制usb？efi中是把英特尔蓝牙的usb屏蔽了的

**Comment by Whozki** [comment]
> 是不是没有重新定制usb？efi中是把英特尔蓝牙的usb屏蔽了的

怎么把屏蔽去掉啊，大佬教教我

**Comment by capricornlee** [comment]
因为我用的是免驱卡的蓝牙所以屏蔽了板载蓝牙的usb，建议重新定制一下自己的USB。
小兵这里有教程：https://blog.daliansky.net/Intel-FB-Patcher-USB-Custom-Video.html

**Comment by Whozki** [comment]
> 因为我用的是免驱卡的蓝牙所以屏蔽了板载蓝牙的usb，建议重新定制一下自己的USB。
> 小兵这里有教程：https://blog.daliansky.net/Intel-FB-Patcher-USB-Custom-Video.html

thx
