### ISSUE TITLE
合盖睡眠问题

### ISSUE THREAD

**Issue by myd986** [capricornlee/LG-Gram13-Z990#9]
合盖只是熄灭屏幕，不会进入睡眠。

**Comment by capricornlee** [comment]
睡眠问题，可能需要自行定制USB，我平常都是合盖就走，是进入睡眠的，否则第二天电量肯定没剩。
再看看hackintool电源选项里，是否有两行红色 修复一下

**Comment by myd986** [comment]
你注意过吗？我现在合上盖子只是熄灭屏幕，睡眠还是等设置的5分钟进入睡眠。我的usb是重新定制过的，该内建的设置好了，hackintool确实有两行红色，修复后变成绿色不过似乎对盒盖睡眠没有改善，能否提供一下寻找问题的方向？

**Comment by capricornlee** [comment]
倒是没留意这点 只是盒盖后第二天电量没掉就没在意了
